### ISSUE TITLE
Build out middleware for API validation

### ISSUE THREAD

**Issue by foerever** [rice-comp413-blue/places.io#10]
You can read about a bit about it here:
https://www.toptal.com/nodejs/secure-rest-api-in-nodejs

Essentially, we want to make sure our validation is self-contained, as in we don't rely on the client to send correct data. For example, the client might try to send a malformed coordinate.

**Comment by XinyangZhu** [comment]
Added a validation middleware and a testing endpoint '/test-middleware'.
