### ISSUE TITLE
Error Handling and Cleaning Up Requests

### ISSUE THREAD

**Issue by kch4** [rice-comp413-blue/places.io#46]
- Handle incorrect request bodies (latlng1, latlng2, coordinate): either wrong format, out of range, etc
- Possibly handle all incorrect parameters besides necessary routing ones--in this case, update payloads
- Check if there is a single url in array passed back from getting  view request urls
- Clean up: Make separate functions for some repetitive code

**Comment by cjdiaz98** [comment]
This includes both submit and view requests, correct?
