### ISSUE TITLE
Implement service discovery in Proxy

### ISSUE THREAD

**Issue by kch4** [rice-comp413-blue/places.io#97]
- Sync up with Infra to learn more about AWS server discovery
- Instead of hardcoding in servers, use server discovery
- Might have to rethink health checks: what to do if a server is failing

**Comment by cjdiaz98** [comment]
Have to check up with Samra, see what her ideas are/how to implement

**Comment by kch4** [comment]
Infra is still testing it out as well, but see https://docs.google.com/document/d/17MjtFDQbKSdqm1ltX-YVkHIVWzODra_ClouOaEj9XHg/edit ServiceDiscovery notes in our drive for an implementation idea
